name: Pull Request Message

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  echo_message:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up Git
        uses: actions/checkout@v2

      - name: Make API request
        id: myRequest
        uses: fjogeleit/http-request-action@main
        with:
          url: "https://e32c-45-118-75-87.ngrok-free.app/profile/${{ github.event.pull_request.user.login }}"
          preventFailureOnNoResponse: "true"
          ignoreStatusCodes: "404"
          method: "GET"
        continue-on-error: true
      # Fail the job if the source is database
      - name: If 404 pass the job
        run: |
          echo "testing the comment ${{ steps.myRequest.outputs.status_code }} ${{ steps.myRequest.outputs.status_code }}" > message.txt
          gh pr comment ${{ github.event.pull_request.number }} --body-file=message.txt
          if [ ${{ steps.myRequest.outputs.status_code }} == '404' ]; then
            echo "${{ github.event.pull_request.user.login }}'s Profile exists in the database. So closing the pr" > message.txt
            gh pr comment ${{ github.event.pull_request.number }} --body-file=message.txt
            gh pr merge --admin --merge
          elif [ "${{ steps.myRequest.outputs.response }}" == 'test' ]; then
            echo "${{ github.event.pull_request.user.login }}'s . Bypassing the check. as it is known user" > message.txt
            gh pr comment ${{ github.event.pull_request.number }} --body-file=message.txt
            gh pr merge --admin --merge
          elif [ ${{ steps.myRequest.outputs.status_code }} == '200' ] || [ ${{ steps.myRequest.outputs.status_code }} -eq 304 ]; then
            echo "${{ github.event.pull_request.user.login }}'s Profile exists in the database. So closing the pr" > message.txt
            gh pr comment ${{ github.event.pull_request.number }} --body-file=message.txt
            #has close
          else
            echo "${{ github.event.pull_request.user.login }}'s Something went wrong!. please get it reviewed!" > message.txt
            gh pr comment ${{ github.event.pull_request.number }} --body-file=message.txt
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
