name: Pull Request Message

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  echo_message:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        uses: actions/checkout@v2

      - name: Echo Message
        run: |
          echo "Hello, this is a GitHub Action!" > message.txt
          echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          gh pr comment ${{ github.event.pull_request.number }} --body-file=message.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
